import { MessageSquare, ExternalLink, Heart } from "lucide-react";

export default function Footer() {
  return (
    <footer className="glass-effect border-t">
      <div className="container mx-auto px-4 py-12">
        <div className="grid md:grid-cols-3 gap-8 mb-8">
          {/* Brand Section */}
          <div className="space-y-4">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-gradient-to-r from-primary to-blue-600 rounded-xl flex items-center justify-center shadow-lg">
                <MessageSquare className="h-5 w-5 text-white" />
              </div>
              <div>
                <h3 className="font-bold gradient-text">feedback.vibespec</h3>
                <p className="text-xs text-muted-foreground">Community Feedback Platform</p>
              </div>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Empowering communities to shape the future of products through collaborative feedback and feature requests.
            </p>
          </div>

          {/* Links Section */}
          <div className="space-y-4">
            <h4 className="font-semibold text-sm">Platform</h4>
            <div className="space-y-2 text-sm text-muted-foreground">
              <div className="flex items-center space-x-2">
                <span>Built with Next.js & shadcn/ui</span>
              </div>
              <div className="flex items-center space-x-2">
                <span>Open source feedback</span>
              </div>
              <div className="flex items-center space-x-2">
                <a href={process.env.NEXT_PUBLIC_GITHUB_URL} target="_blank" rel="noopener noreferrer" className="flex items-center space-x-2 text-sm text-primary hover:text-primary/80 transition-colors group">
                  <span>GitHub Repo</span>
                  <ExternalLink className="h-3 w-3 group-hover:translate-x-0.5 transition-transform" />
                </a>
              </div>
            </div>
          </div>

          {/* VibeSpec Section */}
          <div className="space-y-4">
            <h4 className="font-semibold text-sm">Powered by VibeSpec</h4>
            <div className="space-y-3">
              <a 
                href="https://www.vibespec.build/" 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center space-x-2 text-sm text-primary hover:text-primary/80 transition-colors group"
              >
                <span>Visit VibeSpec</span>
                <ExternalLink className="h-3 w-3 group-hover:translate-x-0.5 transition-transform" />
              </a>
              <p className="text-xs text-muted-foreground leading-relaxed">
                Generate advanced Cursor context files and build MVPs faster with intelligent AI assistance.
              </p>
            </div>
          </div>
        </div>

        {/* Bottom Section */}
        <div className="border-t border-border/40 pt-6 flex flex-col md:flex-row justify-between items-center space-y-2 md:space-y-0">
          <div className="flex items-center space-x-2 text-sm text-muted-foreground">
            <span>Made with</span>
            <Heart className="h-4 w-4 text-red-500" />
            <span>for the developer community</span>
          </div>
          
          <div className="flex items-center space-x-1 text-sm text-muted-foreground">
            <span>Generated by</span>
            <a 
              href="https://www.vibespec.build/" 
              target="_blank" 
              rel="noopener noreferrer"
              className="font-semibold text-primary hover:text-primary/80 transition-colors"
            >
              VibeSpec
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
} 